### PR TITLE
Don't ship 'test' directory in package

### PR DESCRIPTION
**Pull request by adamchainz**
Stops `import test` import these tests wherever `python-libfaketime` is installed :)

### CODE REVIEW

**Comment by simon-weber** [comment]
Whoops, haha. Thanks :grin:

**Comment by simon-weber** [comment]
I should have a chance to cut a release for this later today.

**Comment by adamchainz** [comment]
:scissors: :package: :shipit:

**Comment by simon-weber** [comment]
@adamchainz all set! https://pypi.python.org/pypi/libfaketime/0.1.1

**Comment by adamchainz** [comment]
:rainbow: :rainbow: :rainbow:

**Pull request merged**
