### PR TITLE
Deadlocks from using system level uuid1 generator

### PR DESCRIPTION
**Pull request by jwbixby**
My company uses libfaketime in our large test suite. We have found that deadlocks occur when generating uuid1s from the stdlib while within a fake_time context.

I have been able to reproduce these problems consistently from in our tests and the shell. We are only able to call uuid1() 11 times for a fake time period. In the test below, I'm showing that the same time is used between two context mangers and the deadlock occurs after the 11th call.

```
In [22]: time = datetime.now()
In [23]: with fake_time(time):
    for i in range(10):
        print uuid.uuid1()
   ....:
142d8626-0caa-11e6-b453-080027cebb63
142d8627-0caa-11e6-b453-080027cebb63
142d8628-0caa-11e6-b453-080027cebb63
142d8629-0caa-11e6-b453-080027cebb63
142d862a-0caa-11e6-b453-080027cebb63
142d862b-0caa-11e6-b453-080027cebb63
142d862c-0caa-11e6-b453-080027cebb63
142d862d-0caa-11e6-b453-080027cebb63
142d862e-0caa-11e6-b453-080027cebb63
142d862f-0caa-11e6-b453-080027cebb63
In [24]: with fake_time(time):
    for i in range(10):
        print uuid.uuid1()
   ....:
142d8630-0caa-11e6-b453-080027cebb63
^Z<<--- Deadlock
[1]+  Stopped                 vshell
```

After more investigation, I found that this occurred in my VM, but not my OSX host. After looking at the uuid library, I saw that my OSX computer does not use a system level uuid generator like my VM does. [Relevant Code](https://github.com/python/cpython/blob/a1786b287598baa4a9146c9938c9a667bd98fc00/Lib/uuid.py#L565-L570) This could be a problem with the system level library used in Ubuntu 12.04.5 LTS.

The best fix we could come up with was patching `_uuid_generate_time` to `None` to disable the system level library.

### CODE REVIEW

**Comment by simon-weber** [comment]
Thanks!

**Comment by lchi** [comment]
Great to see this merged!

**Comment by amygdalama** [comment]
My company is also very excited to see this bug fixed! Thanks for your contribution, @jwbixby !

**Comment by amygdalama** [comment]
(We also have a very large test suite.)

**Pull request merged**
