### PR TITLE
Tests - add tox and Travis

### PR DESCRIPTION
**Pull request by adamchainz**
As discussed in #2 it's kinda hard to run the tests. Adding tox and Travis will make this easier.

### CODE REVIEW

**Comment by adamchainz** [comment]
Half working atm - it's just not installing the dependencies yet. I'm not sure if it's to do with the `CustomInstall` or if I'm missing something in `tox.ini`. See https://travis-ci.org/adamchainz/python-libfaketime/builds .

**Comment by simon-weber** [comment]
Try adding something like `pip install .` -- that ought to trigger the compilation of the c code. You may also need to do something to get travis to pull in the submodule.

**Comment by adamchainz** [comment]
Travis automatically pulls in submodules (see log) and `tox` does `setup.py install` as part of its environment creation. In other pure python projects I work on it pulls in `install_requires` just fine which is why I suspect the `CustomInstall` is affecting it in some way. Will have a proper dig later.

**Comment by simon-weber** [comment]
Ah, I see.

Try adding nose to the requirements. I think what's happening is that travis is falling back to the travis-venv nose (see "WARNING:test command found but not installed in testenv"), which then causes the test run to happen outside the tox venv, where contextdecorator isn't installed.

**Comment by adamchainz** [comment]
@simon-weber still failing: https://travis-ci.org/adamchainz/python-libfaketime

It looks like `setup_package` isn't getting called, which is odd. Any experience with this? Do I need an extra nose flag?

**Comment by simon-weber** [comment]
Seems like the install is working ok now, the real problem is a py3k incompatibility error:
```
  File "/home/travis/build/adamchainz/python-libfaketime/test/__init__.py", line 9, in setup_package
    ext_dir = os.path.dirname(libfaketime._lib_addition[sys.platform[:5]].values()[0])
TypeError: 'dict_values' object does not support indexing
```

**Comment by adamchainz** [comment]
Yes it's just working though I don't like invoking `make` from `nose` :/

Will fix the python 3.5 incompatibility

**Comment by adamchainz** [comment]
ok tests are green

**Comment by simon-weber** [comment]
Thanks so much!

**Comment by simon-weber** [comment]
All set: https://travis-ci.org/simon-weber/python-libfaketime.

**Pull request merged**
