### PR TITLE
Use latest version of libfaketime to support mac os x sierra

### PR DESCRIPTION
**Pull request by smaris**

### CODE REVIEW

**Comment by simon-weber** [comment]
My fork has a few changes I'll need to integrate, but thanks for the heads up that the upstream is good to go. I should have time for this tomorrow.

**Comment by smaris** [comment]
There still seems to be an issue. I don't get any errors anymore but the `@fake_time` decorator doesn't seem to work. Using the library directly it works:
`faketime '2015-12-01T11:00:00' gdate`
`faketime '2015-12-01T11:00:00' date`

but not with:
`faketime '2015-12-01T11:00:00' /bin/date`

from what I've seen in code the `gdate` version will be used with this library.

I've provided the exports `DYLD_FORCE_FLAT_NAMESPACE=1`, `DYLD_INSERT_LIBRARIES=[path_to_this_repo/.../lifbfaketime.1.dylib]` and `LD_PRELOAD=[path_to_this_repo/.../lifbfaketime.1.dylib]`.

**Comment by simon-weber** [comment]
Well, the build passed. Locally I'm getting a segfault when running on El Cap, though.

**Comment by simon-weber** [comment]
Oh, I see, the new version isn't backwards compatible. I guess I'll add another submodule and hook it up on pre-sierra versions.

**Comment by simon-weber** [comment]
Ok, I think this works. @smaris can you test this out on sierra for me?

```
pip install git+https://github.com/smaris/python-libfaketime@fix/mac-os-x-sierra#egg=libfaketime
eval $(python-libfaketime)
echo -e 'from libfaketime import fake_time; import datetime\nwith fake_time("2014-01-01 00:00:00"):\n  print datetime.datetime.now()' | python
```

This should print `2014-01-01 00:00:00` if everything went well.

**Comment by smaris** [comment]
Yes it works! good job!

**Comment by simon-weber** [comment]
Great! Thanks for getting everything going. I'll cut a release when I have a chance.

**Comment by simon-weber** [comment]
Ok, 0.4.3 is out.

**Pull request merged**
