### PR TITLE
Python 3 compatibility

### PR DESCRIPTION
**Pull request by dvl**

### CODE REVIEW

**Comment by adamchainz** [comment]
`setup.py` should be updated too to add the correct trove classifiers

**Comment by dvl** [comment]
Done :)

**Comment by simon-weber** [comment]
awesome; thanks!

**Comment by simon-weber** [comment]
I probably won't get to cutting a release for a few days, so you may want to install from source until then with something like https://simon.codes/2014/11/23/git-pip-requirements.html.

**Pull request merged**
